### ISSUE TITLE
Not found: ./checkpoint

### ISSUE THREAD

**Issue by random-yang** [ToolsForAncientChineseText/Text-segmentation#2]
我看了一下，我的理解是没有找到模型？但是我看你们的paper上是说模型也开源了。那么没有模型，是需要自己训练还是？我是这方面是完全的小白，见谅。

**Comment by WeiYi95** [comment]
因为我们目前发现在之前的工作其实是繁简混合的“古文”，存在不严谨之处，所以正在训练纯粹的繁体古文模型，工作正在进行中，如果有进展再行告知。谢谢关注！

**Comment by random-yang** [comment]
@WeiYi95 好的，感谢～

**Comment by leejason** [comment]
> 
> 
> 因为我们目前发现在之前的工作其实是繁简混合的“古文”，存在不严谨之处，所以正在训练纯粹的繁体古文模型，工作正在进行中，如果有进展再行告知。谢谢关注！

不知進展如何? 能否協助提供測試 “古文” 的 checkpoint?
